### PR TITLE
Fix missing status on the ovpn n2n client side

### PR DESCRIPTION
**Pull request by chrko**

### CODE REVIEW

**Comment by mtremer** [comment]
Is there a bug report for this on http://bugzilla.ipfire.org somewhere?

**Comment by chrko** [comment]
Sorry, no. I just wondered, why the graph on `netovpnsrv.cgi` was empty after changing something in the n2n client configuration.
The status line are only added to the client side on the initial upload of the package, 7dfcaef067115be24633f300ef76461ebc2b29c1

**Comment by mtremer** [comment]
Your changes are looking good. I just wanted to know if there is a bug report existing on our bug tracker. If not, please open one so that we can track this bug properly and that I can assign it to the right person.

Usually we do not do GitHub pull requests because I am not able now to steer this patch to the right people.

**Comment by chrko** [comment]
I have created the [bug report](https://bugzilla.ipfire.org/show_bug.cgi?id=10902) and also added the patch there.

**Comment by mtremer** [comment]
Thank you. Discussion will continue on our BZ.

**Pull request closed without merging**
